FROM php:5.6-apache

# RUN apt-get update

# Install minimal packages to build Xdebug
# RUN apt-get install -y libpng-dev libzip-dev git
# RUN docker-php-ext-install zip

# Install Xdebug from source
# RUN git clone -b XDEBUG_2_5_5 https://github.com/xdebug/xdebug.git /root/xdebug \
# && cd /root/xdebug && ./rebuild.sh

# Work directory
# WORKDIR /var/www/html